### PR TITLE
17-quit-prompt + custom_prompt fix

### PR DESCRIPTION
**Pull request by ghost**
Issue #17 
Finally, I am able to implement it. I had to fix, though, a little custom_prompt so as it will be able to react on empty (None) functions and so as it will be able to destroy itself with the mainloop. And also I have created save_and_close, which I don't know if it will be useful in the future (it was useful for me), maybe so as not to pollute the namespace I can put it inside the 'on_closing'?

### CODE REVIEW

**Comment by ghost** [comment]
@PatrickBruso look also my answer in #33

**Review by mrHeavenli — DISMISSED** [review]
Looks great, nice to have a quit prompt.

**Comment by ghost** [comment]
@mrHeavenli Thank you for the feedback. Could you also look at the #33  and tell what do you think and if you think that the changes are needed. Thank you

**Comment by ghost** [comment]
Fellas, tell me if it is better

**Comment by PatrickBruso** [comment]
I'll take a look at this and see.  I want to compare both the customprompt code and the messagebox code as I do see a benefit in being able to change the prompt buttons from yes/no to save/don't save.

**Review by mrHeavenli — APPROVED** [review]
Looks good to me, should work.

**Comment by mrHeavenli** [comment]
@PatrickBruso another good thing about CustomPrompt, is that it is, as the name suggests, _customisable_, tkinter.messagebox is just a collection of common templates for prompts.
Also, as its code is in another file, there aren't any if statements and the code becomes more readable.
I'm sure it will become very useful in the future, however in this case, I do believe it's good to stick with the template provided by tkinter in the case of the quit prompt.
(Sorry if the comment is a bit confusing)

**Comment by PatrickBruso** [comment]
@mrHeavenli I agree, after looking at the commit where it was used to quit I do think it is very useful.  Also, using CustomPrompt in the main application is quite easy, although I still think the CustomPrompt file is fairly confusing for those without a lot of experience.  Maybe we should put in some better documentation/examples in that file.  I will approve this for now and I think later on we can consider switching all the prompts to CustomPrompt.

**Review by PatrickBruso — APPROVED** [review]

**Pull request merged**
